Controllers/SubscriptionController.cs
using Books.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Books.Controllers
{
    public class SubscriptionController : Controller
    {
        private readonly BookDbContext _db;
        private readonly SignInManager<ApplicationUser> signManager;

        public SubscriptionController(BookDbContext db, SignInManager<ApplicationUser> SignManager)
        {
            _db = db;
            signManager = SignManager;



        }
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> subscribe([Bind("email,planId,name,text,price")] Subscription subscriptions)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    subscriptions.email = User.Identity.Name;
                    var searchData = _db.Subscriptions.FirstOrDefault(u => u.planId == subscriptions.planId && u.email == subscriptions.email);
                    if (searchData == null)
                    {
                        //return Ok(new { data = "return null" });
                        subscriptions.Created_at = DateTime.Today;
                        subscriptions.End_at = DateTime.Today.AddMonths(1);
                        _db.Subscriptions.Add(subscriptions);
                        await _db.SaveChangesAsync();
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {

                        return RedirectToAction("error", "subscription");
                    }
                }
                catch (Exception)
                {

                    throw;
                }

            }
            return View();

        }
        
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> unsubscribe([Bind("email,planId,name,text,price")] Subscription subscriptions)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    subscriptions.email = User.Identity.Name;
                    var searchData = _db.Subscriptions.FirstOrDefault(u => u.planId == subscriptions.planId && u.email == subscriptions.email);
                    if (searchData == null)
                    {
                        //return Ok(new { data = "return null" });
                        // return Ok(new { data = searchData });
                     
                        return RedirectToAction("index", "Home");

                    }
                    else
                    {


                        _db.Subscriptions.Remove(searchData);

                        await _db.SaveChangesAsync();
                        ViewData["pagedata"] = "eric";
                        return RedirectToAction("index", "Home");
                    }
                }
                catch (Exception)
                {

                    throw;
                }

            }
            return Ok(new { mydata = "done" });

        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            return View(await _db.Subscriptions.ToListAsync());
            //return View();
            // return RedirectToAction("index", "Home");

        }
        public IActionResult Error()
        {
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> signManager;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Books</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        .form-signin {
    width: 100%;
    max-width: 420px;
    padding: 15px;
    margin: auto;
}
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex ">

                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (signManager.IsSignedIn(User))
                        {

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Subscription" asp-action="index">My Subscription</a>
                        </li>
                        }
                    </ul>
                    <ul class="navbar-nav navbar-right">

                        @if (signManager.IsSignedIn(User))
                        {

                        <li class="nav-item">
                            <form method="post" asp-controller="Account" asp-action="Logout">
                                <button class="nav-link btn btn-link py-0" type="submit" style="width:auto">
                                    Logout @User.Identity.Name
                                </button>
                            </form>
                        </li>
                        }
                        else
                        {

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                        </li>
                        }


                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Books - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>